### ISSUE TITLE
A copyright file?

### ISSUE THREAD

**Issue by NewAlexandria** [squidsoup/mushrooms-russia-history-ebook#1]
What kind of copyright are you intending to add to this work?  

Thanks

**Comment by squidsoup** [comment]
The copyright for the text was not renewed by R. G. Wasson and as far as I have been able to determine, the work is in the public domain. There is an acknowledgement of derivation from the New Alexandria scan/pdf in the eBook notes however. Please let me know if you would like me to adjust the wording, or in fact if you have any objection to my derivation. I've been in touch with Igor Dolgov via email, and he's shown his support for the eBook. I would certainly invite yours as well - in fact, if you still have access to the original scans that would be immensely helpful.

**Comment by squidsoup** [comment]
To further clarify, my intention is to submit the eBook to Project Gutenberg (their copyright team has cleared the work), therefore presumably it would be distributed with the "Project Gutenberg License". I have also been in touch with Valentina's daughter, who had no objections.
